# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newGUIui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtWidgets,QtCore,QtGui
from PyQt5.QtWidgets import QWidget,QCompleter
from PyQt5.QtGui import *
from PyQt5.QtCore import *

from  TestCase_Windows import case3965
from  TestCase_Windows import case3961
from TestCase_Windows.case3961 import testcase3961
from TestCase_Windows.case3965 import testcase3965

items_list=['Jabra BIZ 1500 MS USB Duo',
'Jabra BIZ 1500 MS USB Mono',
'Jabra BIZ 1500 USB Duo',
'Jabra BIZ 1500 USB Mono',
'Jabra BIZ 2300 USB Duo',
'Jabra BIZ 2300 USB Mono',
'Jabra BIZ 2400 II CC USB Mono',
'Jabra BIZ 2400 II CC USB Stereo',
'Jabra BIZ 2400 II Duo',
'Jabra EVOLVE2 75',
'Jabra BIZ 2400 II Mono',
'Jabra BIZ 2400 USB Duo',
'Jabra BIZ 2400 USB Mono',
'Jabra DIAL 550',
'Jabra Engage 50',
'Jabra PanaCast 20',
'Jabra Engage 65',
'Jabra Engage 75',
'Jabra EVOLVE 20 Mono',
'Jabra EVOLVE 20 SE Mono',
'Jabra EVOLVE 20 SE Stereo',
'Jabra EVOLVE 20 Stereo',
'Jabra EVOLVE 30 II Mono',
'Jabra EVOLVE 30 II Stereo',
'Jabra EVOLVE 30 Mono',
'Jabra EVOLVE 30 Stereo',
'Jabra EVOLVE 40 Mono',
'Jabra EVOLVE 40/80 Stereo',
'Jabra EVOLVE 65 Mono',
'Jabra EVOLVE 65 Stereo',
'Jabra Evolve 65e',
'Jabra Evolve 75',
'Jabra Evolve 75e',
'Jabra EVOLVE2 40',
'Jabra Evolve2 65 Deskstand',
'Jabra EVOLVE2 65 Mono',
'Jabra EVOLVE2 65 Stereo',
'Jabra EVOLVE2 85',
'Jabra Evolve2 85 Deskstand',
'Jabra GN2000 MS USB Mono / Duo',
'Jabra GN2000 USB Mono / Duo',
'Jabra GO 6470',
'Jabra HANDSET 450',
'Jabra LINK 220 QD to USB Adapter',
'Jabra LINK 220a QD to USB Adapter',
'Jabra LINK 230 QD to USB Adapter',
'Jabra LINK 260 MS QD to USB Adapter',
'Jabra LINK 260 QD to USB Adapter',
'Jabra LINK 265 QD to USB Training Adapter',
'Jabra LINK 280 QD to USB Adapter',
'Jabra LINK 350 (GO 6430)',
'Jabra LINK 360',
'Jabra LINK 370',
'Jabra LINK 370 MS Teams',
'Jabra Link 380a',
'Jabra LINK 380c',
'Jabra LINK 850',
'Jabra LINK 860',
'Jabra LINK 950',
'Jabra MOTION OFFICE',
'Jabra MOTION UC',
'Jabra PRO 925 Dual Connectivity',
'Jabra PRO 925 Single Connectivity',
'Jabra PRO 930',
'Jabra PRO 935 Dual Connectivity',
'Jabra PRO 935 Single Connectivity',
'Jabra PRO 9450 Series',
'Jabra PRO 9460 Series',
'Jabra PRO 9465 / 9470',
'Jabra SPEAK 410',
'Jabra SPEAK 450 Cisco',
'Jabra SPEAK 510',
'Jabra SPEAK 710',
'Jabra SPEAK 750 MS Teams',
'Jabra SPEAK 750 UC',
'Jabra SPEAK 810',
'Jabra STEALTH UC',
'Jabra SUPREME UC',
'Jabra UC VOICE 150a Duo (Version A)',
'Jabra UC VOICE 150a Mono (Version A)',
'Jabra UC VOICE 150a MS Duo (Version A)',
'Jabra UC VOICE 150a MS Mono (Version A)',
'Jabra UC VOICE 250a (Version A)',
'Jabra UC VOICE 250a MS (Version A)',
'Jabra UC VOICE 550a Duo (Version A)',
'Jabra UC VOICE 550a Mono (Version A)',
'Jabra UC VOICE 550a MS Duo (Version A)',
'Jabra UC VOICE 550a MS Mono (Version A)',
'Jabra UC VOICE 750a Duo (Version A)',
'Jabra UC VOICE 750a Mono (Version A)',
'Jabra UC VOICE 750a MS Duo (Version A)',
'Jabra UC VOICE 750a MS Mono (Version A)',
'Jabra EVOLVE2 30'
]


class Ui_JX_FW(object):


    excuteTestCase = []


    def onUpdateText(self, text):
        """Write console output to text widget."""
        cursor = self.process.textCursor()
        cursor.movePosition(QTextCursor.End)
        cursor.insertText(text)
        self.process.setTextCursor(cursor)

    def pushbuttonEvent(self):
        self.saveDeviceName()
        self.startDownload()

    def saveDeviceName(self):
        DeviceName = self.input_choosedevice.text()
        print("Test device is " + DeviceName)
        fo = open("device.txt", "wt")
        fo.write(DeviceName)
        fo.close()

    def addCase(self,testcase):
        testcase = testcase
        print(testcase)
        Ui_JX_FW.excuteTestCase.append(testcase)
        print(Ui_JX_FW.excuteTestCase)

    def startDownload(self):
        testcaselist=Ui_JX_FW.excuteTestCase
        for testcase in testcaselist:
            testcase = "test"+testcase
            print(testcase)
            eval(testcase)()

    def init_input_choosedevice(self):
        # 增加自动补全
        self.completer = QCompleter(items_list)
        # 设置匹配模式 有三种： Qt.MatchStartsWith 开头匹配（默认） Qt.MatchContains 内容匹配 Qt.MatchEndsWith 结尾匹配
        self.completer.setFilterMode(Qt.MatchContains)
        # 设置补全模式 有三种： QCompleter.PopupCompletion（默认） QCompleter.InlineCompletion  QCompleter.UnfilteredPopupCompletion
        self.completer.setCompletionMode(QCompleter.PopupCompletion)
        # 给lineedit设置补全器
        self.input_choosedevice.setCompleter(self.completer)


    def setupUi(self, JX_FW):
        JX_FW.setObjectName("JX_FW")
        JX_FW.resize(600, 813)
        self.label_chooseDevice = QtWidgets.QLabel(JX_FW)
        self.label_chooseDevice.setGeometry(QtCore.QRect(60, 60, 200, 60))

        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_chooseDevice.setFont(font)
        self.label_chooseDevice.setWordWrap(True)
        self.label_chooseDevice.setObjectName("label_chooseDevice")
        self.input_choosedevice = QtWidgets.QLineEdit(JX_FW)
        self.input_choosedevice.setGeometry(QtCore.QRect(290, 70, 300, 50))
        self.input_choosedevice.setObjectName("input_choosedevice")
        self.label_Windows = QtWidgets.QLabel(JX_FW)
        self.label_Windows.setGeometry(QtCore.QRect(0, 140, 300, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Windows.setFont(font)
        self.label_Windows.setToolTipDuration(0)
        self.label_Windows.setObjectName("label_Windows")
        self.label_Linux = QtWidgets.QLabel(JX_FW)
        self.label_Linux.setGeometry(QtCore.QRect(300, 140, 300, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Linux.setFont(font)
        self.label_Linux.setToolTipDuration(0)
        self.label_Linux.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Linux.setTextFormat(QtCore.Qt.PlainText)
        self.label_Linux.setObjectName("label_Linux")
        self.checkBox = QtWidgets.QCheckBox(JX_FW)
        self.checkBox.setGeometry(QtCore.QRect(20, 180, 271, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 200, 271, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 220, 271, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 240, 271, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 260, 271, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 300, 271, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_7.setGeometry(QtCore.QRect(20, 320, 271, 20))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_8.setGeometry(QtCore.QRect(20, 340, 271, 20))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_9.setGeometry(QtCore.QRect(20, 280, 271, 20))
        self.checkBox_9.setObjectName("checkBox_9")
        self.CheckNetwork = QtWidgets.QPushButton(JX_FW)
        self.CheckNetwork.setGeometry(QtCore.QRect(20, 10, 250, 40))
        self.CheckNetwork.setIconSize(QtCore.QSize(130, 30))
        self.CheckNetwork.setObjectName("CheckNetwork")
        self.CheckNetwork_2 = QtWidgets.QPushButton(JX_FW)
        self.CheckNetwork_2.setGeometry(QtCore.QRect(310, 10, 250, 40))
        self.CheckNetwork_2.setIconSize(QtCore.QSize(130, 30))
        self.CheckNetwork_2.setObjectName("CheckNetwork_2")
        self.checkBox_10 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_10.setGeometry(QtCore.QRect(20, 360, 271, 20))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_11.setGeometry(QtCore.QRect(20, 380, 271, 20))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_12.setGeometry(QtCore.QRect(20, 400, 271, 20))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_13.setGeometry(QtCore.QRect(20, 420, 271, 20))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_14.setGeometry(QtCore.QRect(20, 440, 271, 20))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_15.setGeometry(QtCore.QRect(20, 460, 271, 20))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_16.setGeometry(QtCore.QRect(20, 480, 271, 20))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_17.setGeometry(QtCore.QRect(20, 500, 271, 20))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_18.setGeometry(QtCore.QRect(20, 520, 271, 20))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(JX_FW)
        self.checkBox_19.setGeometry(QtCore.QRect(20, 540, 271, 20))
        self.checkBox_19.setObjectName("checkBox_19")
        self.pushButton = QtWidgets.QPushButton(JX_FW)
        self.pushButton.setGeometry(QtCore.QRect(250, 560, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(JX_FW)
        self.textEdit.setGeometry(QtCore.QRect(10, 650, 581, 161))
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(JX_FW)
        self.lineEdit.setGeometry(QtCore.QRect(10, 610, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.actionCheckall = QtWidgets.QAction(JX_FW)
        self.actionCheckall.setObjectName("actionCheckall")

        #处理事件
        sys.stdout = Stream(newText=self.onUpdateText)
        self.retranslateUi(JX_FW)
        self.init_input_choosedevice()
        self.checkBox.clicked.connect(self.checkBox_2.click)
        self.checkBox.clicked.connect(self.checkBox_3.click)
        self.checkBox_2.clicked.connect(lambda:self.addCase(self.checkBox_2.text()))
        self.checkBox_3.clicked.connect(lambda:self.addCase(self.checkBox_3.text()))
        self.pushButton.clicked.connect(lambda:self.pushbuttonEvent())


        QtCore.QMetaObject.connectSlotsByName(JX_FW)

    def retranslateUi(self, JX_FW):
        _translate = QtCore.QCoreApplication.translate
        JX_FW.setWindowTitle(_translate("JX_FW", "Jabra Xpress Downlod tool"))
        self.label_chooseDevice.setText(_translate("JX_FW", "Choose Device :"))
        self.label_Windows.setText(_translate("JX_FW", "                     Windows Cases"))
        self.label_Linux.setText(_translate("JX_FW", "                            Linux Cases"))
        self.checkBox.setText(_translate("JX_FW", "Select All"))
        self.checkBox_2.setText(_translate("JX_FW", "case3961"))
        self.checkBox_3.setText(_translate("JX_FW", "case3965"))
        self.checkBox_4.setText(_translate("JX_FW", "case3966"))
        self.checkBox_5.setText(_translate("JX_FW", "case3969"))
        self.checkBox_6.setText(_translate("JX_FW", "case4128"))
        self.checkBox_7.setText(_translate("JX_FW", "case5509"))
        self.checkBox_8.setText(_translate("JX_FW", "Case5665"))
        self.checkBox_9.setText(_translate("JX_FW", "Case4090"))
        self.CheckNetwork.setText(_translate("JX_FW", "CheckNetwork"))
        self.CheckNetwork_2.setText(_translate("JX_FW", "Check Chrome Driver"))
        self.checkBox_10.setText(_translate("JX_FW", "Case7195"))
        self.checkBox_11.setText(_translate("JX_FW", "Case7196"))
        self.checkBox_12.setText(_translate("JX_FW", "Case10449"))
        self.checkBox_13.setText(_translate("JX_FW", "Case10312"))
        self.checkBox_14.setText(_translate("JX_FW", "Case3965_32b"))
        self.checkBox_15.setText(_translate("JX_FW", "Case3966_32b"))
        self.checkBox_16.setText(_translate("JX_FW", "Case4090_32b"))
        self.checkBox_17.setText(_translate("JX_FW", "Case3965_32b"))
        self.checkBox_18.setText(_translate("JX_FW", "Case3965_32b"))
        self.checkBox_19.setText(_translate("JX_FW", "Case3965_32b"))
        self.pushButton.setText(_translate("JX_FW", "Start"))
        self.lineEdit.setText(_translate("JX_FW", "Download progress"))
        self.actionCheckall.setText(_translate("JX_FW", "Checkall"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_JX_FW()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
